// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz97Scj8D0IQCc3M8B-QLk9ivfhEBnDq4',
    appId: '1:186244424243:android:76649403eae6bbd2e8f946',
    messagingSenderId: '186244424243',
    projectId: 'flexivel',
    storageBucket: 'flexivel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnbcyRsjOSoooDBQXQPBlaOGPeILpKeJw',
    appId: '1:186244424243:ios:644d500d4011c3bae8f946',
    messagingSenderId: '186244424243',
    projectId: 'flexivel',
    storageBucket: 'flexivel.firebasestorage.app',
    iosBundleId: 'com.example.flexivel',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWP1UBwSA_DNuk5sTkZRPULglDO1WcNIU',
    appId: '1:186244424243:web:96fd921783ff98f1e8f946',
    messagingSenderId: '186244424243',
    projectId: 'flexivel',
    authDomain: 'flexivel.firebaseapp.com',
    databaseURL: 'https://flexivel-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flexivel.firebasestorage.app',
    measurementId: 'G-C83NWWWZ5X',
  );

}